name: Auto-Release

on:
  push:
    branches:
      - main

jobs:
  auto-release:
    uses: baumrock/RockMigrations/.github/workflows/auto-release.yml@main
    with:
      email: "office@baumrock.com"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
